server:
  error:
    include-exception: true
    include-stacktrace: always
    whitelabel:
      enabled: true
    path: /error

application:
  crypto:
    password: e94a67d8-6a9c-450c-8149-1145fc9ecace

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    cache: false

  datasource:
    url: jdbc:mysql://110.10.189.141:3306?characterEncoding=utf8
    username: croiUser
    password: croi@dmin2023
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      max-lifetime: 300000
      idle-timeout: 10000

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 500
        hibernate.format_sql: false
    defer-datasource-initialization: true

logging:
  level:
    #    org.springframework: info
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
    #    org.springframework.web.reactive.function.client.DefaultExchangeFunction: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace