INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME) VALUES ('허', '균');
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME) VALUES ('홍', '명희');
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME) VALUES ('김', '혜남');
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME) VALUES ('김', '호연');
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME) VALUES ('장', '재형');

INSERT INTO BOOK (TITLE, AUTHOR_ID) VALUES ('홍길동전', 1);
INSERT INTO BOOK (TITLE, AUTHOR_ID) VALUES ('한정록', 1);
INSERT INTO BOOK (TITLE, AUTHOR_ID) VALUES ('남궁선생전', 1);
INSERT INTO BOOK (TITLE, AUTHOR_ID) VALUES ('임꺽정전', 2);
INSERT INTO BOOK (TITLE, AUTHOR_ID) VALUES ('만일 내가 인생을 다시 산다면', 3);
INSERT INTO BOOK (TITLE, AUTHOR_ID) VALUES ('서른살이 심리학에게 묻다', 3);
INSERT INTO BOOK (TITLE, AUTHOR_ID) VALUES ('보이지 않는 것에 의미가 있다', 3);
INSERT INTO BOOK (TITLE, AUTHOR_ID) VALUES ('당신과 나 사이', 3);
INSERT INTO BOOK (TITLE, AUTHOR_ID) VALUES ('어른이 되면 괜찮을 줄 알았다', 3);
INSERT INTO BOOK (TITLE, AUTHOR_ID) VALUES ('불편한 편의점', 4);
INSERT INTO BOOK (TITLE, AUTHOR_ID) VALUES ('연적', 4);
INSERT INTO BOOK (TITLE, AUTHOR_ID) VALUES ('마흔에 읽는 니체', 5);
